FROM node:20-slim

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install && chown -R node:node /app/node_modules

COPY --chown=node:node . .

EXPOSE 3000

CMD ["sh", "/app/entrypoint.sh"]
